// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa6PMgt03q9ddJ1b-YAYD2dtRG33eMPDM',
    appId: '1:538377515024:web:67ccaaa3a12f028f1b1a95',
    messagingSenderId: '538377515024',
    projectId: 'auth-3d0ba',
    authDomain: 'auth-3d0ba.firebaseapp.com',
    storageBucket: 'auth-3d0ba.appspot.com',
    measurementId: 'G-5LV9K7WY1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdjmG6lRKvsiW7wL1XF8PiE2GjHhbgMCw',
    appId: '1:538377515024:android:ae1a8c40af978cf81b1a95',
    messagingSenderId: '538377515024',
    projectId: 'auth-3d0ba',
    storageBucket: 'auth-3d0ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMgPrvFTj-7s8VgRySKMzKhGENmehfX3E',
    appId: '1:538377515024:ios:6a73a29c7bb147681b1a95',
    messagingSenderId: '538377515024',
    projectId: 'auth-3d0ba',
    storageBucket: 'auth-3d0ba.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMgPrvFTj-7s8VgRySKMzKhGENmehfX3E',
    appId: '1:538377515024:ios:6a73a29c7bb147681b1a95',
    messagingSenderId: '538377515024',
    projectId: 'auth-3d0ba',
    storageBucket: 'auth-3d0ba.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
